# Generated by Django 3.1.7 on 2021-06-12 11:50

import SystemDesign.utility
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', max_length=5000, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Class',
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(db_column='value', max_length=5000, verbose_name='value')),
                ('class_subclass', models.ForeignKey(db_column='class', on_delete=django.db.models.deletion.CASCADE, related_name='subClasses', related_query_name='subClass', to='classDiagram.class', verbose_name='class')),
            ],
            options={
                'verbose_name': 'Subclass',
                'verbose_name_plural': 'Subclasses',
                'db_table': 'subclass',
            },
        ),
        migrations.CreateModel(
            name='ClassDiagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', SystemDesign.utility.SVGAndImageField(upload_to='classDiagram', verbose_name='image')),
                ('uml', SystemDesign.utility.SVGAndImageField(upload_to='uml', verbose_name='uml')),
                ('problem', models.ForeignKey(db_column='problem', on_delete=django.db.models.deletion.CASCADE, related_name='ClassDiagrams', related_query_name='ClassDiagram', to='problem.problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'ClassDiagram',
                'verbose_name_plural': 'ClassDiagrams',
                'db_table': 'classdiagram',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='class_diagram',
            field=models.ForeignKey(db_column='Class', on_delete=django.db.models.deletion.CASCADE, related_name='Classes', related_query_name='Class', to='classDiagram.classdiagram', verbose_name='class Diagram'),
        ),
    ]
