# Generated by Django 3.1.7 on 2021-06-03 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDiagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(db_column='classes', max_length=5000, verbose_name='classes')),
                ('image', models.ImageField(upload_to='classDiagram', verbose_name='image')),
                ('uml', models.ImageField(upload_to='uml', verbose_name='uml')),
                ('problem', models.ForeignKey(db_column='problem', on_delete=django.db.models.deletion.CASCADE, related_name='ClassDiagrams', related_query_name='ClassDiagram', to='problem.problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'ClassDiagram',
                'verbose_name_plural': 'ClassDiagrams',
                'db_table': 'class_diagram',
            },
        ),
    ]
