# Generated by Django 3.1.7 on 2021-06-03 22:11

import classDiagram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classDiagram', '0002_auto_20210603_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdiagram',
            name='uml',
            field=models.FileField(upload_to='uml', verbose_name='uml'),
        ),
    ]
