# Generated by Django 3.1.7 on 2021-06-05 11:50

import SystemDesign.utility
import classDiagram.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classDiagram', '0003_auto_20210603_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdiagram',
            name='image',
            field=SystemDesign.utility.SVGAndImageField(upload_to='classDiagram', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='classdiagram',
            name='uml',
            field=SystemDesign.utility.SVGAndImageField(upload_to='uml', validators=[classDiagram.models.ClassDiagram.validate_uml], verbose_name='uml'),
        ),
    ]
