# Generated by Django 3.1.7 on 2021-06-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classDiagram', '0004_auto_20210605_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.TextField(db_column='name', max_length=5000, verbose_name='name'),
        ),
    ]
