# Generated by Django 3.1.7 on 2021-06-10 08:10

import classDiagram.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classDiagram', '0005_auto_20210605_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdiagram',
            name='image',
            field=classDiagram.models.SVGAndImageField(upload_to='classDiagram', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='classdiagram',
            name='uml',
            field=classDiagram.models.SVGAndImageField(upload_to='uml', verbose_name='uml'),
        ),
    ]
