# Generated by Django 3.1.7 on 2021-06-04 12:49

import activityDiagram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityDiagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydiagram',
            name='image',
            field=models.FileField(upload_to='activityDiagram', verbose_name='image'),
        ),
    ]
