# Generated by Django 3.1.7 on 2021-06-05 11:50

import SystemDesign.utility
import activityDiagram.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityDiagram', '0002_auto_20210604_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydiagram',
            name='image',
            field=SystemDesign.utility.SVGAndImageField(upload_to='activityDiagram', verbose_name='image'),
        ),
    ]
