# Generated by Django 3.1.7 on 2021-06-12 11:50

import SystemDesign.utility
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.TextField(db_column='actor', max_length=5000, verbose_name='actor')),
            ],
            options={
                'verbose_name': 'Actors',
                'verbose_name_plural': 'Actors',
                'db_table': 'actor',
            },
        ),
        migrations.CreateModel(
            name='UseCaseDiagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', SystemDesign.utility.SVGAndImageField(upload_to='usecases', verbose_name='image')),
                ('problem', models.ForeignKey(db_column='problem', on_delete=django.db.models.deletion.CASCADE, related_name='UseCaseDiagrams', related_query_name='UseCaseDiagram', to='problem.problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'UseCaseDiagram',
                'verbose_name_plural': 'UseCaseDiagrams',
                'db_table': 'usecasediagram',
            },
        ),
        migrations.CreateModel(
            name='UseCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_case', models.TextField(db_column='use_case', max_length=5000, verbose_name='use_case')),
                ('usecasediagram', models.ForeignKey(db_column='usecasediagram', on_delete=django.db.models.deletion.CASCADE, related_name='usecases', related_query_name='usecase', to='useCaseDiagram.usecasediagram', verbose_name='usecases')),
            ],
            options={
                'verbose_name': 'UseCases',
                'verbose_name_plural': 'UseCases',
                'db_table': 'use_case',
            },
        ),
        migrations.CreateModel(
            name='SubUsecase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(db_column='value', max_length=5000, verbose_name='value')),
                ('usecase', models.ForeignKey(db_column='usecase', on_delete=django.db.models.deletion.CASCADE, related_name='subUseCases', related_query_name='subUseCase', to='useCaseDiagram.usecases', verbose_name='usecase')),
            ],
            options={
                'verbose_name': 'SubUsecase',
                'verbose_name_plural': 'SubUsecases',
                'db_table': 'sub_usecase',
            },
        ),
        migrations.CreateModel(
            name='ActorSubtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(db_column='value', max_length=5000, verbose_name='value')),
                ('actor', models.ForeignKey(db_column='actor', on_delete=django.db.models.deletion.CASCADE, related_name='actorSubtasks', related_query_name='actorSubtask', to='useCaseDiagram.actors', verbose_name='actor')),
            ],
            options={
                'verbose_name': 'ActorSubtask',
                'verbose_name_plural': 'ActorSubtasks',
                'db_table': 'actor_subtask',
            },
        ),
        migrations.AddField(
            model_name='actors',
            name='usecasediagram',
            field=models.ForeignKey(db_column='usecasediagram', on_delete=django.db.models.deletion.CASCADE, related_name='actors', related_query_name='actor', to='useCaseDiagram.usecasediagram', verbose_name='usecasediagram'),
        ),
    ]
