# Generated by Django 3.1.7 on 2021-06-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useCaseDiagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecases',
            name='usecasediagram',
            field=models.ForeignKey(db_column='usecasediagram', on_delete=django.db.models.deletion.CASCADE, related_name='usecases', related_query_name='usecase', to='useCaseDiagram.usecasediagram', verbose_name='usecases'),
        ),
    ]
