# Generated by Django 3.1.7 on 2021-06-05 11:50

import SystemDesign.utility
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useCaseDiagram', '0002_auto_20210604_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecasediagram',
            name='image',
            field=SystemDesign.utility.SVGAndImageField(upload_to='usecases', verbose_name='image'),
        ),
    ]
