# Generated by Django 3.1.7 on 2021-06-10 07:07

import SystemDesign.utility
from django.db import migrations
import useCaseDiagram.models


class Migration(migrations.Migration):

    dependencies = [
        ('useCaseDiagram', '0004_auto_20210605_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecasediagram',
            name='image',
            field=SystemDesign.utility.SVGAndImageField(upload_to='usecases', verbose_name='image'),
        ),
    ]
