# Generated by Django 3.1.7 on 2021-06-11 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useCaseDiagram', '0005_auto_20210610_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorSubtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(db_column='task', max_length=5000, verbose_name='task')),
                ('actor', models.ForeignKey(db_column='actor', on_delete=django.db.models.deletion.CASCADE, related_name='actorSubtasks', related_query_name='actorSubtask', to='useCaseDiagram.actors', verbose_name='actor')),
            ],
            options={
                'verbose_name': 'ActorSubtask',
                'verbose_name_plural': 'ActorSubtasks',
                'db_table': 'actor_subtask',
            },
        ),
    ]
