# Generated by Django 3.1.7 on 2021-06-12 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useCaseDiagram', '0006_actorsubtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubUsecase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(db_column='value', max_length=5000, verbose_name='value')),
                ('usecase', models.ForeignKey(db_column='usecase', on_delete=django.db.models.deletion.CASCADE, related_name='subUseCases', related_query_name='subUseCase', to='useCaseDiagram.usecases', verbose_name='usecase')),
            ],
            options={
                'verbose_name': 'SubUsecase',
                'verbose_name_plural': 'SubUsecases',
                'db_table': 'sub_usecase',
            },
        ),
    ]
