# Generated by Django 3.1.7 on 2021-06-12 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.TextField(db_column='requirement', max_length=5000, verbose_name='requirement')),
                ('problem', models.ForeignKey(db_column='problem', on_delete=django.db.models.deletion.CASCADE, related_name='SystemRequirements', related_query_name='SystemRequirement', to='problem.problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'SystemRequirements',
                'verbose_name_plural': 'SystemRequirements',
                'db_table': 'system_requirement',
            },
        ),
    ]
