# Generated by Django 3.1.7 on 2021-06-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemRequirements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemrequirement',
            name='requirement',
            field=models.TextField(db_column='requirement', max_length=5000, verbose_name='requirement'),
        ),
    ]
