# Generated by Django 3.1.7 on 2021-06-10 11:41

import SystemDesign.utility
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0003_auto_20210605_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceDiagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_column='name', max_length=500, verbose_name='description')),
                ('image', SystemDesign.utility.SVGAndImageField(upload_to='sequenceDiagram', verbose_name='image')),
                ('problem', models.ForeignKey(db_column='problem', on_delete=django.db.models.deletion.CASCADE, related_name='SequenceDiagram', related_query_name='SequenceDiagram', to='problem.problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'SequenceDiagram',
                'verbose_name_plural': 'SequenceDiagrams',
                'db_table': 'sequence_diagram',
            },
        ),
    ]
