# Generated by Django 3.1.7 on 2021-06-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='java',
            field=models.TextField(db_column='java', max_length=5000, verbose_name='java'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='python',
            field=models.TextField(db_column='python', max_length=5000, verbose_name='python'),
        ),
    ]
