# Generated by Django 3.1.7 on 2021-06-12 11:50

import SystemDesign.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=500, verbose_name='Problem Name')),
                ('description', models.TextField(db_column='description', max_length=5000, verbose_name='Problem Description')),
                ('image', SystemDesign.utility.SVGAndImageField(upload_to='problem', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
                'db_table': 'problem',
            },
        ),
    ]
