# Generated by Django 3.1.7 on 2021-06-05 11:50

import SystemDesign.utility
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='image',
            field=SystemDesign.utility.SVGAndImageField(upload_to='problem', verbose_name='image'),
        ),
    ]
